### PR TITLE
added fade in for tourtips

### PR DESCRIPTION
**Pull request by britztopher**
Added the fade in css for tour tips

### CODE REVIEW

**Comment by britztopher** [comment]
@gustvao is doing this just in css what we are looking for?  If not, I think we can add css rules right in the directive.

**Comment by gustvao** [comment]
hey @britztopher ,

I couldnt run grunt serve on it, it is breaking, can you pls fix it?

``` js
Running "autoprefixer:dist" (autoprefixer) task
Warning: Can't parse CSS: missing '}' near line 17:3 Use --force to continue.
```

**Comment by britztopher** [comment]
@gustvao Im not getting any errors on my branch.  Did you merge my code in?  If so did you do a grunt build to replace the css in the build folder.  `grunt serve` works for me.  

```
Running "autoprefixer:dist" (autoprefixer) task
Prefixed file ".tmp/styles/tour/tour.css" created.

Done, without errors.
```

**Comment by britztopher** [comment]
@gustvao still having issues with PR?

**Comment by gustvao** [comment]
hey @britztopher , yes.

this is what I receive after running grunt build

screenshot-guga guga-hp-pavilion-dv2700 -angular-angular-tour

**Comment by gustvao** [comment]
hey @britztopher any luck with this?

**Comment by britztopher** [comment]
@gustvao  Yeah im trying to get the error to reproduce, but I am getting clean build.  Ill try getting this done by tomorrow

**Comment by britztopher** [comment]
@gustvao i upgraded some things and will be using this in my project now.  I would accept this pr then we can talk about future of this project (if there is one)  I really like this little library, so lets see if we can hurdle this minor speed bump

**Pull request merged**
