### PR TITLE
enabled smooth scrolling.

### PR DESCRIPTION
**Pull request by kisonay**
Got both horizontal and vertical scrolling working.

### CODE REVIEW

**Comment by gustvao** [comment]
hey @kisonay sorry it took me a while to take a look at this..

could you pls resubmit without re-indenting the file? the way you did it the whole file is conflicted and I cant easily distinguish between what is conflicting because of your code from what is merely indentation..

**Comment by kisonay** [comment]
I don't remember what changes I made and haven't had the time to go through it all and re-apply them to a clean copy of the file which I didn't mess with the indentation. I will try to get to it this week.

**Comment by gustvao** [comment]
ok. tks

**Comment by kisonay** [comment]
Think I fixed everything, let me know if you still have issues. I didn't commit any updates to the dist folder but can do that if you would like.

**Comment by kisonay** [comment]
went ahead and resolved conflicts.

**Comment by gustvao** [comment]
thank you!

**Pull request merged**
